### ISSUE TITLE
Create sensible "register" route (use bcrypt)

### ISSUE THREAD

**Issue by MahdiurRahman** [MahdiurRahman/OnTimeServer#9]
Create a register route with proper logic, should follow extension "**/api/register**"
Route should:
1. check users for duplicates
2. encrypt/hashed password w/ bcrypt https://www.npmjs.com/package/bcrypt

**Comment by KevinLu19** [comment]
I can figure out the mechanics for Expressjs and work on this part. 
(I'm more experienced in Python so ima have to look it up)
